# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a27312d408f6639f5f21388de178c5dce21be73124b23f8ad2999dda6b021aee5044eae5098cb128d003bfae48c77ac03d149fc93c67ace8100e5f262a49e797

test:
  secret_key_base: 6bc03155f6ea34529afdfbbd82c9e264698e1336bbe18eed832d0f66aeb4c5c1b615e7d759d25ee8a41da1eab258d9ae115c41fa35851f55867687b97cc5e337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
